server:
  port: 18080
  

spring:
  datasource:
    url: jdbc:h2:mem:TEST;DB_CLOSE_DELAY=-1;
    username: sa 
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.H2Dialect
  messages:
    basename: messages,config.i18n.messages